import { GlobalContextProvider } from "./Context"
export const metadata = {
  title: 'Jogo da Velha',
  description: 'Generated by Lucas',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body> 
        <GlobalContextProvider>
          {children}
        </GlobalContextProvider>
      </body>
    </html>
  )
}
